### ISSUE TITLE
Local hardhat development Error: resolver or addr is not configured for ENS name (argument="name", value="BOSON_TOKEN", code=INVALID_ARGUMENT, version=contracts/5.4.1)

### ISSUE THREAD

**Issue by marc4gov** [bosonprotocol/contracts#130]
```
(base) marc@MacBook-Pro-van-Marc contracts % ./go contracts:run
Configuring NVM if present.
Checking for system dependencies.
All system dependencies present. Continuing.
Installing bundler.
Installing ruby dependencies.
Starting rake.
npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@2. I'll try to do my best with it!
audited 2385 packages in 9.982s

171 packages are looking for funding
  run `npm fund` for details

found 4287 vulnerabilities (12 low, 1031 moderate, 3244 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm run contracts:run

> y@1.0.0 contracts:run /Users/marc/Projects/boson/contracts
> hardhat compile && hardhat deploy

Nothing to compile
No need to generate any newer typings.
$ Setting initial values ...

$ ERC1155ERC721:  ApprovalForAll approved VoucherKernel: true
$ ERC1155ERC721:  LogVoucherKernelSet at: 0x4FF0B67c6eE79Ed6d739419D70c7299b7285b3Cc
$ ERC1155ERC721:  LogCashierSet at: 0x39C1c6bFc6f1EbBD4e45C11F44099066B919E577

$ VoucherKernel LogBosonRouterSet at: 0x1507e4D16E01981f6A3Da847C9367DE0A40a6671
$ VoucherKernel LogCashierSet at: 0x39C1c6bFc6f1EbBD4e45C11F44099066B919E577

$ Cashier LogBosonRouterSet at: 0x1507e4D16E01981f6A3Da847C9367DE0A40a6671
$ Cashier LogTokenContractSet at: 0x5958E222Cf51a94Abc1228a3d709bbCeD9f660b7
An unexpected error occurred:

Error: resolver or addr is not configured for ENS name (argument="name", value="BOSON_TOKEN", code=INVALID_ARGUMENT, version=contracts/5.4.1)
    at Logger.makeError (/Users/marc/Projects/boson/contracts/node_modules/@ethersproject/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
    at Logger.throwError (/Users/marc/Projects/boson/contracts/node_modules/@ethersproject/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
    at Logger.throwArgumentError (/Users/marc/Projects/boson/contracts/node_modules/@ethersproject/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:229:21)
    at /Users/marc/Projects/boson/contracts/node_modules/@ethersproject/contracts/src.ts/index.ts:129:16
    at step (/Users/marc/Projects/boson/contracts/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/marc/Projects/boson/contracts/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/Users/marc/Projects/boson/contracts/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at listOnTimeout (internal/timers.js:523:9) {
  reason: 'resolver or addr is not configured for ENS name',
  code: 'INVALID_ARGUMENT',
  argument: 'name',
  value: 'BOSON_TOKEN'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! y@1.0.0 contracts:run: `hardhat compile && hardhat deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the y@1.0.0 contracts:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marc/.npm/_logs/2021-09-15T08_17_40_357Z-debug.log
rake aborted!
Command failed with status (1): [npm run contracts:run...]
/Users/marc/Projects/boson/contracts/Rakefile:46:in `block (2 levels) in <top (required)>'
/Users/marc/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/Users/marc/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
Tasks: TOP => contracts:run
(See full trace by running task with --trace)
```

**Comment by hswopeams** [comment]
Copy `.env.example` to `.env`

To run locally, you don't need to fill in any values. You should be able to use it as-is.
If you want to deploy to another environment you need to provide your Infura API key, your Etherscan API key, and the private key fo the deployer account you want to use. 

You can use the testnet Boson token address listed here for testnet deployments:
https://github.com/bosonprotocol/contracts/releases/tag/v0.1.0

**Comment by marc4gov** [comment]
Ok, I did copy `.env.example` to `.env` but I needed to put in a valid token address for BOSON in order for the command to run properly. This is the `.env` I used:
```
INFURA_API_KEY=INFURA_API_KEY
PK=PRIVATE_KEY
ETHERSCAN_API_KEY=ETHERSCAN_API_KEY
BOSON_TOKEN=0x1b48e27D7ABaDf2f5A5f14975Cb9D4E457dF5111
```
and gave me this result:
```
(base) marc@MacBook-Pro-van-Marc contracts % ./go contracts:run
Configuring NVM if present.
Checking for system dependencies.
All system dependencies present. Continuing.
Installing bundler.
Installing ruby dependencies.
Starting rake.
npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@2. I'll try to do my best with it!
audited 2385 packages in 10.338s

171 packages are looking for funding
  run `npm fund` for details

found 4287 vulnerabilities (12 low, 1031 moderate, 3244 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm run contracts:run

> y@1.0.0 contracts:run /Users/marc/Projects/boson/contracts
> hardhat compile && hardhat deploy

Nothing to compile
No need to generate any newer typings.
$ Setting initial values ...

$ ERC1155ERC721:  ApprovalForAll approved VoucherKernel: true
$ ERC1155ERC721:  LogVoucherKernelSet at: 0x4FF0B67c6eE79Ed6d739419D70c7299b7285b3Cc
$ ERC1155ERC721:  LogCashierSet at: 0x39C1c6bFc6f1EbBD4e45C11F44099066B919E577

$ VoucherKernel LogBosonRouterSet at: 0x1507e4D16E01981f6A3Da847C9367DE0A40a6671
$ VoucherKernel LogCashierSet at: 0x39C1c6bFc6f1EbBD4e45C11F44099066B919E577

$ Cashier LogBosonRouterSet at: 0x1507e4D16E01981f6A3Da847C9367DE0A40a6671
$ Cashier LogTokenContractSet at: 0x5958E222Cf51a94Abc1228a3d709bbCeD9f660b7

FundLimitsOracle Contract Address:  0x6DfC760cf9BBaE3Bd4b6DfCE536aa372E9A611a9
ERC1155ERC721 Contract Address:  0x5958E222Cf51a94Abc1228a3d709bbCeD9f660b7
VoucherKernel Contract Address:  0x4FF0B67c6eE79Ed6d739419D70c7299b7285b3Cc
Cashier Contract Address:  0x39C1c6bFc6f1EbBD4e45C11F44099066B919E577
Boson Router Contract Address:  0x1507e4D16E01981f6A3Da847C9367DE0A40a6671

real	0m20.556s
user	0m23.640s
sys	0m2.557s```

**Comment by hswopeams** [comment]
On this page there's a list of our contract addresses deployed on Rinkeby:
https://github.com/bosonprotocol/contracts/releases/tag/v0.1.0

The last one is a Boson Token address that can be used for testing against
